version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - "/"
      - "/fuzz/"
      - "/xtask/"
    schedule:
      interval: weekly
    cooldown:
      default-days: 5
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    cooldown:
      default-days: 5
