version: 2
updates:
  - package-ecosystem: cargo
    directories:
      - "/"
      - "/fuzz/"
      - "/xtask/"
    schedule:
      interval: weekly
  - package-ecosystem: uv
    directories:
      - "/ci/"
    schedule:
      interval: weekly
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
