image:
  file: .gitpod.Dockerfile

tasks:
  - init: cargo build
    command: cargo watch -s 'reset; cargo run'

vscode:
  extensions:
    - hbenl.vscode-test-explorer@2.17.0:ZA2HdWojYevHSV7TPmY3cA==
    - Swellaby.vscode-rust-test-adapter@0.11.0:Xg+YeZZQiVpVUsIkH+uiiw==
    - serayuzgur.crates@0.4.9:neXjmFo2gFaLS/dBOkKnpQ==
    - belfz.search-crates-io@1.2.1:kSLnyrOhXtYPjQpKnMr4eQ==
    - bungcip.better-toml@0.3.2:3QfgGxxYtGHfJKQU7H0nEw==
