language: rust
dist: bionic

env:
  global:
    - HOST=x86_64-unknown-linux-gnu
    - RUSTFLAGS='-D warnings'
    - TOKEI_VERSION=v11.1.0

jobs:
  include:
    # Linux
    - env: TARGET=x86_64-unknown-linux-gnu
    - env: TARGET=x86_64-unknown-linux-musl
    - env: TARGET=i686-unknown-linux-gnu

    # OSX
    - env: TARGET=x86_64-apple-darwin
      os: osx

    # Windows
    - env: TARGET=x86_64-pc-windows-gnu
      os: windows
    - env: TARGET=x86_64-pc-windows-msvc
      os: windows
    - env: TARGET=i686-pc-windows-msvc
      os: windows

    # Testing on the nightly channel
    - env: TARGET=x86_64-unknown-linux-gnu
      rust: nightly
      allow_failures: true
    - env: TARGET=x86_64-apple-darwin
      os: osx
      rust: nightly
      allow_failures: true
    - env: TARGET=x86_64-pc-windows-gnu
      os: windows
      rust: nightly
      allow_failures: true

    # Static checks
    - name: LOC
      before_install: skip
      install: skip
      before_script: |
        mkdir -pv ~/.local/bin \
        && curl -L "https://github.com/XAMPPRocky/tokei/releases/download/${TOKEI_VERSION}/tokei-${TARGET:-$HOST}.tar.gz" \
        | tar -xzvf - -C ~/.local/bin tokei
      script: ./count_loc.sh
    - name: Rustfmt and Clippy (Linux)
      # Install the rustfmt and clippy components for the nightly channel
      # Sometimes, not all components are available in any given nightly, which causes errors such as
      # https://github.com/ilai-deutel/kibi/issues/24. Therefore, we use the `--allow-downgrade` flag to downgrade
      # the version if either rustfmt or clippy are not available for this or any newer nightly.
      # In the future, `rustup component add` will have a `--allow-downgrade` flag
      # (see https://github.com/rust-lang/rustup/issues/2146), but in the meantime we use this work-around:
      before_install: rustup toolchain install $TRAVIS_RUST_VERSION --allow-downgrade -c rustfmt -c clippy
      install: skip
      script: |
        cargo fmt -- --check \
        && cargo clippy --all-targets -- -D warnings
      rust: nightly
    - name: Clippy (Windows)
      before_install: rustup toolchain install $TRAVIS_RUST_VERSION --allow-downgrade -c clippy
      install: skip
      script: cargo clippy --all-targets -- -D warnings
      rust: nightly
      env: TARGET=x86_64-pc-windows-gnu
      os: windows
#    - name: Dependency Audit
#      install: cargo install cargo-audit
#      script: cargo audit
#      cache: cargo

  fast_finish: true

before_install: ci/before_install.sh

cache: false

install: |
  cargo build --target "${TARGET:-$HOST}" --verbose
  cargo run -- --version

script: cargo test

before_deploy: ci/before_deploy.sh

deploy:
  provider: releases
  api_key:
    secure: Va5HQGJoUwfnsxN8L1zI2RkSt1s0az7v7/NHxQMTv8SffaDOJuhbeWXsr9vFHNIE8wUC2mkLOd6rAGZ9YCtRUKS4nAucPk0gUD083y34j1DMLh6ycMjFtuWdWCaUMHaVqZjXPMCdeL7xZ6SuWqjhBDcOhDW3c63/caCSY6BlLQ2EFfT/GRscO2AzrRW0emHU3S8d9BgTX3YxSvJJnBZaUdLEbHQdLw/6m30MgaUwnPodxjRqzxNSJ+yReDJqwYvLCYCdYvNLlhA5MXM4GfgOsIWFdS1nMUyVKjpDf80f/BRUSLPst9uZ/6EBnFsUOTF7Vfw6FgNknNaqk7dHatIy5bWjjB6z8SPZAwzfnYCFNpFu6567/9i0PUxWd0g8L1lRGf0P+Y2rMJmV2LWpL4zjb7lDUHf9Hbg3ueY/yLguhi/ic7U2+ok2S4OCH+uDs1uSsekpyxYhqHL4zcFxtUTi1zasRI1NEVJr9CcAVoR4p/83N6rX5/0xR7pdhCfDGTlBQQH0AjHU/q8GhVw2mVlyQqefNBszjHrG9tI1oWcRmSruWMG7HX4m3BAci2T1/MlJSmUiwQ27eaBHLw6fROvkH2RD3kowRsM3oCRN6OQLf/HD5OnLfqKhGEaYlAfzpf9O6tQZSCHbIST4rhLYdCkGofNiPjSa3tErmoxWFNhm57E=
  file_glob: true
  file: release_files/*
  skip_cleanup: true
  draft: true
  on:
    tags: true
    condition: $TRAVIS_RUST_VERSION = stable && -n "$TARGET"
