[graph]
all-features = true

[advisories]
unmaintained = "workspace"

[bans]
multiple-versions = 'deny'
wildcards = 'deny'

[bans.build]
executables = "deny"
interpreted = "allow"
include-workspace = false

[licenses]
allow = [
    "MIT",
    "Apache-2.0",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
