version = 1

[[annotations]]
path = [
    "**/.gitignore",
    "**/Cargo.toml",
    "**/Cargo.lock",
    ".allstar/*.yaml",
    ".cargo/config.toml",
    ".cargo/mutants.toml",
    ".config/nextest.toml",
    ".github/CODEOWNERS",
    ".github/**.yml",
    ".vscode/settings.json",
    "assets/recording.cast",
    "assets/*.png",
    "assets/*.webm",
    "ci/*.json",
    "scripts/termframe/*",
    "scripts/flake.lock",
    "syntax.d/*.ini",
    ".all-contributorsrc",
    ".markdownlint.json",
    "clippy.toml",
    "config_example.ini",
    "deny.toml",
    "kibi.desktop",
    "rustfmt.toml",
]
SPDX-FileCopyrightText = "2020 Ilaï Deutel & Kibi Contributors"
SPDX-License-Identifier = "MIT or Apache-2.0"
