name: Appstream metadata validation

# Run when the Appstream metadata is updated, or once a month
on:
  pull_request:
    paths:
      - "kibi.metainfo.xml"
      - ".github/workflows/appstream.yml"
  schedule:
    - cron: "0 0 1 * *"

permissions:
  contents: read

jobs:
  appstream_validation:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          persist-credentials: false
      - name: Install Appstream validator
        run: |
          sudo apt-get install flatpak
          flatpak --user remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
          flatpak --user install -y flathub org.freedesktop.appstream-glib
      - name: Validate Appstream metadata
        run: flatpak run org.freedesktop.appstream-glib validate kibi.metainfo.xml
