on:
  push:
    branches:
      - "master"
  pull_request:
    paths:
      - "**.rs"
      - ".github/workflows/loc.yml"

name: LOC

permissions:
  contents: read

jobs:
  check_lines_of_code:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          egress-policy: audit
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Setup cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4  # v2.9.1
        with:
          prefix-key: rust-stable
      - name: Check LOC <= 1024
        run: cargo xtask count-loc
