on:
  pull_request:
    paths:
      - '**.sh'
      - '.github/workflows/shellcheck.yml'

name: 'ShellCheck'

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run ShellCheck
      uses: ludeeus/action-shellcheck@master
      env:
        SHELLCHECK_OPTS: --enable all
